from isaaclab.terrains.terrain_generator_cfg import TerrainGeneratorCfg

from dawn.sim.mdp.terrains.sub_terrains_cfg import (
    HfGapTerrainCfg,
    HfInvertedPyramidStairsTerrainCfg,
    HfParkourTerrainCfg,
    HfPyramidSlopedTerrainCfg,
    HfPyramidStairsTerrainCfg,
    HfRandomUniformTerrainCfg,
    HfStepTerrainCfg,
)

terrain_generator_cfg = TerrainGeneratorCfg(
    size=(8.0, 8.0),
    border_width=15.0,
    num_rows=10,
    num_cols=20,
    horizontal_scale=0.05,
    vertical_scale=0.005,
    slope_threshold=1.5,
    use_cache=False,
    sub_terrains={
        "flat": HfRandomUniformTerrainCfg(
            proportion=0.1,
            border_width=0.0,
            randomize_height_variation=False,
            height_variation_range=(0.01, 0.01),
            height_step=0.005,
            downsampled_scale=0.10,
            add_random_uniform_terrain=True,
        ),
        "slope": HfPyramidSlopedTerrainCfg(
            proportion=0.1,
            border_width=0.0,
            slope_range=(0.0, 0.4),
            platform_width=3.0,
            add_random_uniform_terrain=True,
            height_variation_range=(0.01, 0.01),
        ),
        "gap": HfGapTerrainCfg(
            proportion=0.2,
            border_width=0.0,
            num_gaps=4,
            gap_height_range=(0.25, 0.35),
            gap_size_range=(0.05, 0.50),
            gap_width_range=(0.8, 1.0),
            stone_depth_range=(1.1, 1.3),
            height_variation_range=(0.01, 0.01),
        ),
        "step": HfStepTerrainCfg(
            proportion=0.2,
            border_width=0.0,
            num_steps=2,
            step_height_range_easy=(0.01, 0.10),
            step_height_range_hard=None,
            step_width_range=(0.8, 1.0),
            use_curriculum_step_depth=False,
            step_depth_range=(1.1, 1.3),
            step_dis_range=(1.5, 2.0),
            height_variation_range=(0.01, 0.01),
        ),
        "up_stairs_0.3": HfInvertedPyramidStairsTerrainCfg(
            proportion=0.1,
            step_height_range=(0.05, 0.18),
            step_width=0.3,
            platform_width=3.0,
            border_width=0.1,
            add_random_uniform_terrain=False,
        ),
        "up_stairs_0.32": HfInvertedPyramidStairsTerrainCfg(
            proportion=0.1,
            step_height_range=(0.05, 0.18),
            step_width=0.32,
            platform_width=3.0,
            border_width=0.1,
            add_random_uniform_terrain=False,
        ),
        "up_stairs_0.34": HfInvertedPyramidStairsTerrainCfg(
            proportion=0.1,
            step_height_range=(0.05, 0.18),
            step_width=0.3,
            platform_width=3.0,
            border_width=0.1,
            add_random_uniform_terrain=False,
        ),
        "down_stairs_0.3": HfPyramidStairsTerrainCfg(
            proportion=0.1,
            step_height_range=(0.05, 0.18),
            step_width=0.3,
            platform_width=3.0,
            border_width=0.1,
            add_random_uniform_terrain=False,
        ),
        "down_stairs_0.32": HfPyramidStairsTerrainCfg(
            proportion=0.1,
            step_height_range=(0.05, 0.18),
            step_width=0.32,
            platform_width=3.0,
            border_width=0.1,
            add_random_uniform_terrain=False,
        ),
        "down_stairs_0.34": HfPyramidStairsTerrainCfg(
            proportion=0.1,
            step_height_range=(0.05, 0.18),
            step_width=0.34,
            platform_width=3.0,
            border_width=0.1,
            add_random_uniform_terrain=False,
        ),
        "huddle_0.6": HfParkourTerrainCfg(
            proportion=0.2,
            border_width=0.0,
            height_variation_range=(0.01, 0.01),
            huddle_size=0.6,
        ),
        "huddle_0.7": HfParkourTerrainCfg(
            proportion=0.2,
            border_width=0.0,
            height_variation_range=(0.01, 0.01),
            huddle_size=0.7,
        ),
        "huddle_0.8": HfParkourTerrainCfg(
            proportion=0.2,
            border_width=0.0,
            height_variation_range=(0.01, 0.01),
            huddle_size=0.8,
        ),
        "huddle_0.9": HfParkourTerrainCfg(
            proportion=0.2,
            border_width=0.0,
            height_variation_range=(0.01, 0.01),
            huddle_size=0.9,
        ),
    },
)
